name: CI

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Show available SDKs
        run: xcodebuild -showsdks

      - name: Build macOS
        run: |
          xcodebuild -resolvePackageDependencies \
            -project Demo/Demo-macOS/Demo-macOS.xcodeproj \
            -scheme Demo-macOS

          xcodebuild -project Demo/Demo-macOS/Demo-macOS.xcodeproj \
            -scheme Demo-macOS \
            -configuration Release \
            CODE_SIGN_IDENTITY="-" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            build

      - name: Build iOS
        run: |
          xcodebuild -resolvePackageDependencies \
            -project Demo/Demo-iOS/Demo-iOS.xcodeproj \
            -scheme Demo-iOS

          xcodebuild -project Demo/Demo-iOS/Demo-iOS.xcodeproj \
            -scheme Demo-iOS \
            -configuration Release \
            CODE_SIGN_IDENTITY="-" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            build


      - name: Build Succeeded
        run: |
          echo "Build completed successfully."